<a href="https://colab.research.google.com/github/zhirobyte/AllAboutBugBounty/blob/master/Assesment_2_Faiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [120]:
# import paket

import pandas as pd
import numpy as np


In [121]:
# read direktori file csv

liver = pd.read_csv("data_liver_resample.csv")
liver


v1  v2   v3   v4   v5   v6   v7   v8   v9   v10  v11
0    28   1  0.6  0.1  137   22   16  4.9  1.9  0.60    2
1    58   1  0.8  0.2  130   24   25  7.0  4.0  1.30    1
2    53   1  0.9  0.2  210   35   32  8.0  3.9  0.90    2
3    70   0  1.3  0.3  690   93   40  3.6  2.7  0.70    1
4    22   1  2.2  1.0  215  159   51  5.5  2.5  0.80    1
..   ..  ..  ...  ...  ...  ...  ...  ...  ...   ...  ...
578  60   0  3.2  1.8  750   79  145  7.8  3.2  0.69    1
579  22   0  0.9  0.3  179   18   21  6.7  3.7  1.20    2
580  23   1  2.3  0.8  509   28   44  6.9  2.9  0.70    2
581  46   0  3.3  1.5  172   25   41  5.6  2.4  0.70    1
582  37   0  0.8  0.2  195   60   40  8.2  5.0  1.50    2

[583 rows x 11 columns]

In [122]:
# read direktori file csv
liver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   v1      583 non-null    int64  
 1   v2      583 non-null    int64  
 2   v3      583 non-null    float64
 3   v4      583 non-null    float64
 4   v5      583 non-null    int64  
 5   v6      583 non-null    int64  
 6   v7      583 non-null    int64  
 7   v8      583 non-null    float64
 8   v9      583 non-null    float64
 9   v10     583 non-null    float64
 10  v11     583 non-null    int64  
dtypes: float64(5), int64(6)
memory usage: 50.2 KB


In [123]:
#ini untuk menentukan variable independet = v7 merupakan tingkat jumlah asparate pada darah 
x = liver.drop(["v7"], axis = 1)
x.head()


v1  v2   v3   v4   v5   v6   v8   v9  v10  v11
0  28   1  0.6  0.1  137   22  4.9  1.9  0.6    2
1  58   1  0.8  0.2  130   24  7.0  4.0  1.3    1
2  53   1  0.9  0.2  210   35  8.0  3.9  0.9    2
3  70   0  1.3  0.3  690   93  3.6  2.7  0.7    1
4  22   1  2.2  1.0  215  159  5.5  2.5  0.8    1

In [124]:
#menentukan dependen pada variable yakni v7
y = liver["v7"]
y.head()

0    16
1    25
2    32
3    40
4    51
Name: v7, dtype: int64

In [125]:
#import model paket menggunakan sklearn
from sklearn.model_selection import train_test_split


In [126]:
#pada kolom ini dibagi data menjadi data training dan testing

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.)


ValueError: ignored

In [ ]:
#mengaktifkan paket dan syntax untuk mengubah skala data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)


In [ ]:
#running skleearn paket Knn
from sklearn.neighbors import KNeighborsClassifier


In [127]:
#aktifin fungsi klasifikasi knn dengan v4 yakni 
knn = KNeighborsClassifier (n_neighbors=5)


In [128]:
#masukkan data train pada klasifikasi knn

knn.fit(x_train, y_train)

KNeighborsClassifier()

In [129]:
#menentukan prediksinya
y_pred = knn.predict (x_test)
y_pred 

array([ 24, 141,  18,  39,  79,  27, 141,  88,  32,  23,  23,  30,  67,
        17,  41,  41,  16,  30,  14,  22,  58,  13,  23,  23,  24,  23,
        21,  22, 105,  50, 220,  39,  15,  26,  24,  30,  30, 143,  21,
       103,  15, 104,  14,  16, 108,  48,  39,  14,  34,  29,  16,  23,
        51,  16,  68,  51,  32,  50, 231])

In [130]:
# menentukan probabilitas prediksinya
knn.predict_proba(x_test)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [131]:
#import paket untuk melihat akurasi prediksi dengan data aktual
from sklearn.metrics import classification_report, confusion_matrix

# printout hasil prediksi matrixs
print(confusion_matrix(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [132]:
#akurasi hasil prediksi
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          13       0.00      0.00      0.00         1
          14       0.33      1.00      0.50         1
          15       0.50      1.00      0.67         1
          16       0.00      0.00      0.00         0
          17       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         0
          19       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         2
          21       0.00      0.00      0.00         2
          22       0.50      1.00      0.67         1
          23       0.17      1.00      0.29         1
          24       0.33      0.33      0.33         3
          26       0.00      0.00      0.00         0
          27       0.00      0.00      0.00         0
          28       0.00      0.00      0.00         1
          29       1.00      0.50      0.67         2
          30       0.25      1.00      0.40         1
          31       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1